import type { AuthService } from '../services/auth/AuthService';
import type { InputManager } from '../core/input/InputManager';
import type { JoystickCalibrationController } from '../core/input/JoystickCalibrationController';
import type { PerformanceMonitor } from '../core/performance/PerformanceMonitor';
import type { FrameRateController } from '../core/performance/FrameRateController';
import type { ManagedPlayerRepository } from '../services/cloud/CloudSaveTypes';
import type { SceneManager } from '../core/scenes/SceneManager';
import type { AssetManager } from '../core/assets/AssetManager';
import type { AudioManager } from '../core/audio/AudioManager';
import type { GameDataRegistry } from '../game/data/GameDataRegistry';
import type { GraphicsQualityController } from '../core/graphics/GraphicsQualityController';
import type { OperationsContentService } from '../services/operations/OperationsContentService';
import type { RankingService } from '../services/ranking/RankingService';
import type { AccessibilityController } from '../core/accessibility/AccessibilityController';
import type { AdaptivePerformanceController } from '../core/performance/AdaptivePerformanceController';
import type { MobileViewportController } from '../core/layout/MobileViewportController';
import type { PlayerArtVariantController } from '../core/presentation/PlayerArtVariantController';
import type { DeviceQaSessionRecorder } from '../core/performance/DeviceQaSessionRecorder';
import type { HapticFeedbackController } from '../core/accessibility/HapticFeedbackController';
import type { LiveRegionAnnouncer } from '../core/accessibility/LiveRegionAnnouncer';

export interface AppContext {
  readonly auth: AuthService;
  readonly input: InputManager;
  readonly joystickCalibration: JoystickCalibrationController;
  readonly performance: PerformanceMonitor;
  readonly frameRate: FrameRateController;
  readonly graphicsQuality: GraphicsQualityController;
  readonly accessibility: AccessibilityController;
  readonly adaptivePerformance: AdaptivePerformanceController;
  readonly mobileViewport: MobileViewportController;
  readonly playerArtVariant: PlayerArtVariantController;
  readonly deviceQaSession: DeviceQaSessionRecorder;
  readonly haptics: HapticFeedbackController;
  readonly liveAnnouncer: LiveRegionAnnouncer;
  readonly gameData: GameDataRegistry;
  readonly playerRepository: ManagedPlayerRepository;
  readonly scenes: SceneManager;
  readonly assets: AssetManager;
  readonly audio: AudioManager;
  readonly operationsContent: OperationsContentService;
  readonly ranking: RankingService;
}
